version: '3'
services:
  app:
    image: 919446158824.dkr.ecr.us-east-1.amazonaws.com/repoflow-container-graph:1.10.1-master
    env_file:
      - .env
    volumes:
     - /home/victor/nodeflow/workspace:/home/node/workspace
     - /home/victor/.gitconfig:/home/node/.gitconfig
     - /home/victor/.ssh:/home/node/.ssh
    environment:
     - REPOFLOW_WORKSPACE=/home/node/workspace
    ports:
     - "${SERVICE_PORT}:${SERVICE_PORT}"
